### PR TITLE
Perf: Performance improvements for large websites and Gatsby V4 support

### PR DESCRIPTION
**Pull request by yogeshkotadiya**
### Description

Significant performance improvement for large website (Pages > 20000) 

Result:

```
Test 1: with 50000 Pages
Current version: 394.057s
With Performance fix: 6.842s
```

Compatibility with Gatsby V4

Checklist:
- [x] Maintain compatibility
- [x] Tests passing

### CODE REVIEW

**Comment by yogeshkotadiya** [comment]
@aileen Can you please review this?

**Review by aileen — APPROVED** [review]
Thank you @yogeshkotadiya! This looks great!!! Sorry it took so long to get to this. Please feel free to self merge it and ship 🙌

**Comment by yogeshkotadiya** [comment]
@aileen Can you publish a new version? I don't have permission to publish.

**Comment by aileen** [comment]
@yogeshkotadiya done ✅

**Pull request merged**
