### PR TITLE
Serve sitemap.xsl via relative url

### PR DESCRIPTION
**Pull request by karolis-sh**
Fixes https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/issues/7

Did a couple extra commits:
- added lock file as [it should be committed](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/) (I assumed you're using `yarn` as it was the only ignored lockfile)
- removed & ignored build output as it's anti-pattern to include build output in the repository (it's hard to contribute when you have modified files right after `yarn install`)

Also a suggestion - if you'd swap `import` with `require` you could drop the babel step as node 8+ should handle all the code natively.

### CODE REVIEW

**Comment by AileenCGN** [comment]
> Also a suggestion - if you'd swap import with require you could drop the babel step as node 8+ should handle all the code natively.

Great suggestion! I believe it's a bit more than just swapping import with require, but definitely something we could tackle soon!

Thanks for the PR! Looks good to me!

**Comment by AileenCGN** [comment]
@karolis-sh I had to put the build output back, as the plugin wouldn't work anymore. Need to find out why, because other plugins also work like without it 🤔

**Comment by karolis-sh** [comment]
@AileenCGN did you run the build command before publishing? you could troubleshoot with `npm pack` to see what get's bundled to the package.

**Comment by AileenCGN** [comment]
@karolis-sh hmm, that's the output of `npm pack` when the files are **not** included in `.gitignore`:

```bash
> gatsby-plugin-advanced-sitemap@1.4.2 prepare /Users/aileen/code/gatsby-plugin-advanced-sitemap
> cross-env NODE_ENV=production yarn build

yarn run v1.15.2
$ babel src --out-dir . --ignore **/__tests__
Successfully compiled 8 files with Babel.
✨  Done in 1.11s.
npm notice
npm notice 📦  gatsby-plugin-advanced-sitemap@1.4.2
npm notice === Tarball Contents ===
npm notice 1.5kB   package.json
npm notice 151B    .babelrc
npm notice 96B     .eslintrc.js
npm notice 5.0kB   BaseSiteMapGenerator.js
npm notice 646B    defaults.js
npm notice 14.2kB  gatsby-node.js
npm notice 874B    gatsby-ssr.js
npm notice 9B      index.js
npm notice 2.1kB   IndexMapGenerator.js
npm notice 1.1kB   LICENSE
npm notice 4.1kB   README.md
npm notice 1.0kB   SiteMapGenerator.js
npm notice 2.2kB   SiteMapManager.js
npm notice 327B    utils.js
npm notice 144.0kB yarn.lock
npm notice 2.7kB   .github/CONTRIBUTING.md
npm notice 1.1kB   .github/ISSUE_TEMPLATE/---bug-report.md
npm notice 924B    .github/ISSUE_TEMPLATE/--anything-else.md
npm notice 342B    src/.editorconfig
npm notice 1.7kB   src/.eslintrc.js
npm notice 4.4kB   src/BaseSiteMapGenerator.js
npm notice 601B    src/defaults.js
npm notice 10.1kB  src/gatsby-node.js
npm notice 510B    src/gatsby-ssr.js
npm notice 1.4kB   src/IndexMapGenerator.js
npm notice 272B    src/SiteMapGenerator.js
npm notice 1.7kB   src/SiteMapManager.js
npm notice 224B    src/utils.js
npm notice 6.2kB   static/sitemap.xsl
npm notice === Tarball Details ===
npm notice name:          gatsby-plugin-advanced-sitemap
npm notice version:       1.4.2
npm notice filename:      gatsby-plugin-advanced-sitemap-1.4.2.tgz
npm notice package size:  73.4 kB
npm notice unpacked size: 209.3 kB
npm notice shasum:        edbb93135b74147ce3449689adfba281e801f3cb
npm notice integrity:     sha512-IF8j9jhvIZJHe[...]A2SGLIMDp4KLA==
npm notice total files:   29
npm notice
gatsby-plugin-advanced-sitemap-1.4.2.tgz
```

And this is the output with the files included in `.gitignore`:

```bash
> gatsby-plugin-advanced-sitemap@1.4.2 prepare /Users/aileen/code/gatsby-plugin-advanced-sitemap
> cross-env NODE_ENV=production yarn build

yarn run v1.15.2
$ babel src --out-dir . --ignore **/__tests__
Successfully compiled 8 files with Babel.
✨  Done in 1.06s.
npm notice
npm notice 📦  gatsby-plugin-advanced-sitemap@1.4.2
npm notice === Tarball Contents ===
npm notice 1.5kB   package.json
npm notice 151B    .babelrc
npm notice 96B     .eslintrc.js
npm notice 9B      index.js
npm notice 1.1kB   LICENSE
npm notice 4.1kB   README.md
npm notice 144.0kB yarn.lock
npm notice 2.7kB   .github/CONTRIBUTING.md
npm notice 1.1kB   .github/ISSUE_TEMPLATE/---bug-report.md
npm notice 924B    .github/ISSUE_TEMPLATE/--anything-else.md
npm notice 342B    src/.editorconfig
npm notice 1.7kB   src/.eslintrc.js
npm notice 6.2kB   static/sitemap.xsl
npm notice === Tarball Details ===
npm notice name:          gatsby-plugin-advanced-sitemap
npm notice version:       1.4.2
npm notice filename:      gatsby-plugin-advanced-sitemap-1.4.2.tgz
npm notice package size:  60.7 kB
npm notice unpacked size: 163.8 kB
npm notice shasum:        5ec6d4595fadb5d50008718bad195f02376135c6
npm notice integrity:     sha512-jxfBJQnQPw9mN[...]VKGt5ozQbfCOQ==
npm notice total files:   13
npm notice
gatsby-plugin-advanced-sitemap-1.4.2.tgz
```

Seems like they're missing in the pack 😔

**Comment by karolis-sh** [comment]
Yeah, just create a `.npmignore` file and include the build files explicitly:

```
!BaseSiteMapGenerator.js
!IndexMapGenerator.js
!SiteMapGenerator.js
!SiteMapManager.js
!defaults.js
!gatsby-node.js
!gatsby-ssr.js
!utils.js
```

**Comment by AileenCGN** [comment]
Ah!!! Of course!!! Thank you!!!

**Comment by karolis-sh** [comment]
Glad I could help 😉

**Pull request merged**
