### PR TITLE
fix: solve some errors about url.resolve which is deprecated

### PR DESCRIPTION
**Pull request by CBW2007**

### CODE REVIEW

**Comment by Enter-tainer** [comment]
see https://nodejs.org/api/url.html#url_url_resolve_from_to

image

**Comment by yogeshkotadiya** [comment]
@CBW2007 Thank you for your contribution.
Unfortunately, the legacy URL module was not deprecated until Node 11. And since this plugin supports Node 10 we can't merge this for V1.x.x.
Soon we will release V2 in which we will upgrade to Gatsby 3 and drop Node 10 support. We can merge this PR in V2.

**Comment by aileen** [comment]
Hey @yogeshkotadiya 

I've just updated all deps and release this version as 2.0. Think we can merge this PR now?

**Comment by Enter-tainer** [comment]
Hi, @yogeshkotadiya 

Any idea about this PR? Seems that we are now at V2. Maybe we can merge it now.

**Review by yogeshkotadiya — APPROVED** [review]
LGTM 👍

**Pull request merged**
